testing smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -374,30 +374,49 @@ jobs:
       - empty-bucket
 
 
-#   smoke-test:
-#     docker:
-#       # Lightweight Docker image 
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Get backend url
-#           command: |
-#             # your code here
-#       - run:
-#           name: Backend smoke test.
-#           command: |
-#             # your code here
-#       - run:
-#           name: Frontend smoke test.
-#           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure  
-#       - destroy-environment:
-#           id: $CIRCLE_WORKFLOW_ID
+  smoke-test:
+    docker:
+      # Lightweight Docker image 
+      - image: alpine
+    steps:
+      # Checkout code from git
+      - run:
+          name: Install dependencies
+          command: |
+            # your code here
+            apk add curl
+      - run:
+          name: Get backend url
+          command: |
+            # your code here
+            BACKEND_IP=$(curl -H "token: ${CIRCLE_WORKFLOW_ID}" --request GET https://api.memstash.io/values/deployment)
+            echo "I think the Backend IP is ${BACKEND_IP}"
+            echo ${BACKEND_IP} > /tmp/backend
+            echo -n "The file /tmp/backend contains IP:"
+            cat /tmp/backend
+      - run:
+          name: Backend smoke test.
+          command: |
+            # your code here
+            BACKEND_URL="https://$(cat /tmp/backend)/api/status"
+            echo "curl-ing ${BACKEND_URL}"
+            if curl ${BACKEND_URL}
+              then exit 0
+              else exit 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            # your code here
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID}.s3-website-us-west-2.amazonaws.com"
+            echo "curl-ing ${URL}"
+            if curl ${URL} | grep -q "Welcome"
+              then exit 0
+              else exit 1
+            fi
+      # Here's where you will add some code to rollback on failure  
+      - destroy-environment
+      - empty-bucket
 
 #   cloudfront-update:
 #     docker:
@@ -462,8 +481,8 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
-      # - smoke-test:
-      #     requires: [deploy-backend, deploy-frontend]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
       # - cloudfront-update:
       #     requires: [smoke-test]
       # - cleanup:
